issues:
  exclude-rules:
    - path: /
      linters:
        - nosnakecase
        - nlreturn
        - forcetypeassert
        - ifshort
        - scopelint
        - varnamelen
        - lll
        - testpackage
        - gomnd
        - wsl
        - gochecknoglobals
        - paralleltest
        - wsl
        - dupl
        - dupword

linters:
  enable-all: true
  enable:
    - revive

issues:
  include:
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015