issues:
  exclude-rules:
    - path: /
      linters:
        - nosnakecase
        - forcetypeassert
        - ifshort
        - scopelint
        - varnamelen
        - testpackage
        - gomnd
        - wsl
        - gochecknoglobals
        - cyclop
        - paralleltest
        - wsl
        - dupl
        - dupword

linters:
  enable-all: true
