issues:
  include:
    - EXC0001
    - EXC0002
    - EXC0003
    - EXC0004
    - EXC0005
    - EXC0006
    - EXC0007
    - EXC0008
    - EXC0009
    - EXC0010
    - EXC0011
    - EXC0012
    - EXC0013
    - EXC0014
  exclude-rules:
    - path: /
      linters:
        - nosnakecase
        - nlreturn
        - forcetypeassert
        - ifshort
        - scopelint
        - varnamelen
        - lll
        - testpackage
        - gomnd
        - wsl
        - gochecknoglobals
        - paralleltest
        - wsl
        - dupl
        - dupword

linters:
  enable-all: true
  enable:
    - revive
    - misspell
